version: "3.5"
services:
  rabbitmq:
    image: rabbit-image
    container_name: "rabbitmq-con"
    build:
      context: ./
      dockerfile: ./Dockerfile.Rabbit
    ports:
      - 5672:5672
      - 15672:15672
