version: "3.5"
services:
  db:
    image: mysql-img
    container_name: "mysql-con"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.MySql
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass

  adminer:
    image: adminer
    container_name: "adminer-con"
    restart: always
    ports:
      - 8080:8080