services:
  service1:
    container_name: service1-con
    image: rabbit-service1-img
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: service1
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Rabbit
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - rabbitmq
      - seq
  service2:
    container_name: service2-con
    image: rabbit-service2-img
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: service2
    ports:
      - 5002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Rabbit
      - ASPNETCORE_URLS=http://*:5002
    depends_on:
      - rabbitmq
      - seq
  service3:
    container_name: service3-con
    image: rabbit-service3-img
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: service3
    ports:
      - 5003:5003
    environment:
      - ASPNETCORE_ENVIRONMENT=Rabbit
      - ASPNETCORE_URLS=http://*:5003
    depends_on:
      - rabbitmq
      - seq
  rabbitmq:
    image: rabbit-image
    container_name: "rabbitmq"
    build:
      context: ./
      dockerfile: ./rabbit.Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
  seq:
    image: datalust/seq:latest
    container_name: seq-con
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
