apiVersion: v1
kind: Service
metadata:
  name: apiservice-svc
spec:
  type: NodePort
  selector:
    app: apiservice
  ports:
    - name: apiservice-port
      port: 80
      targetPort: 80
      protocol: TCP